### ISSUE TITLE
UX loading indicator on add to campaign button is in an odd alignment.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-campaign-admin#142] opened 2019-05-07 21:42 UTC
When adding a saved (but unpublished) page to a campaign, I am presented with a modal to select the campaign.
After selecting the campaign from the dropdown component, I can click the green "add" button.
When I click the add button the text is replaced with what looks like a loading indicator consisting of three dots that pulsate in sequence, however this is partially obscured in the top left corner of the green add button, cropped by its border.

**Comment by robbieaverill** [comment] 2019-05-07 21:42
Duplicate of https://github.com/silverstripe/silverstripe-admin/issues/862

**Closed by robbieaverill** 2019-05-07 21:42 UTC
