### ISSUE TITLE
"Save" button should revert back to pristine state after successful submission

### ISSUE THREAD

**Issue by phalkunz** [silverstripe/silverstripe-campaign-admin#41] opened 2017-08-04 00:01 UTC
Original issue: https://github.com/silverstripe/silverstripe-campaign-admin/issues/16

Discuss this issue with @unclecheese. We should `initialize` the form after each submission:
https://github.com/erikras/redux-form/issues/1994
https://github.com/erikras/redux-form/pull/2426

**Comment by chillu** [comment] 2017-08-22 02:23
@unclecheese @flamerohr Can you please doublecheck might be sorted?

**Comment by unclecheese** [comment] 2017-08-22 02:28
Have tested and this is not resolved. Saving the campaign edit form leaves the button permanently in the "save" state.

**Comment by flamerohr** [comment] 2017-08-28 21:29
duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/163

**Comment by flamerohr** [comment] 2017-09-04 22:19
Have tested and has been fixed with https://github.com/silverstripe/silverstripe-admin/pull/216/files#diff-7eed84efcf9a5970aee3afb2aa621b33R122

**Closed by flamerohr** 2017-09-04 22:19 UTC
Labels: affects/v4, impact/medium, type/bug
