### ISSUE TITLE
BUG Weird scrollbar on nearly every campaign admin section

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-campaign-admin#92] opened 2018-03-29 01:53 UTC
![image](https://user-images.githubusercontent.com/936064/38065664-ed53e4a2-3360-11e8-9bb3-9f5a205cf8a6.png)

1.x-dev branch

**Comment by chillu** [comment] 2019-01-14 03:18
There's also vertical scrollbars

![image](https://user-images.githubusercontent.com/111025/51095214-fc6fa380-1817-11e9-9636-54ef7a2ae7a9.png)

**Comment by robbieaverill** [comment] 2019-02-01 15:20
I accidentally fixed the vertical scrollbar bug in #132. I can't reproduce the horizontal scrollbars any more.

**Comment by chillu** [comment] 2019-02-04 08:37
The vertical scrollbars are still there, and they look a bit whacky. But it can be "fixed" by dismissing the dialog, which most people using this section will do on first opening it. So I'm going to close this

**Closed by chillu** 2019-02-04 08:37 UTC
Labels: affects/v4, change/patch, effort/easy, impact/low, type/UX, type/bug, type/frontend
